version: '3.8'

services:
  chatapi-dev:
    build: .
    container_name: chatapi
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_DATABASE_NAME: VIDEO_INFOMATION
      PORT: 5050
    
    # Dev stuff
    stdin_open: true
    tty: true
    develop:
      watch: 
        # sync static content
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
            - dev.docker-compose.yml
            - prod.docker-compose.yml
            - .env.*
            - .env
            - .dockerignore
        - action: rebuild
          path: ./package.json
    command: ["pnpm", "run", "dev"]

    ports:
      - '5050:5050'
    networks:
      -  db_backend-net

networks:
  db_backend-net:
    external: true