version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    environment:
      - PORT=8080
    ports:
      - '8080:8080'
    networks:
      -  db_backend-net

networks:
  db_backend-net:
    external: true