version: '3.8'

# From: https://geshan.com.np/blog/2022/01/redis-docker/
# From: https://stackoverflow.com/questions/29377853/how-can-i-use-environment-variables-in-docker-compose
# How to use environment variables

# Notes
# - https://stackoverflow.com/questions/77355287/adding-local-minio-host-to-mc-configuration-failed-to-add-temporary-minio-ser
# - https://medium.com/@randy.hamzah.h/running-minio-server-with-docker-compose-54bab3afbe31

services:
  redis-stream:
    image: redis:6.2-alpine
    # restart: always
    ports:
      - '6379:6379'
    # Have to set memory size of redis for BullMQ to work properly
    # From: https://peterkellner.net/2023/09/24/Managing-Redis-Memory-Limits-with-Docker-Compose/ 
    command: redis-server --save 20 1  --maxmemory 1GB --maxmemory-policy noeviction --loglevel warning
    volumes: 
      - redis-stream:/data
  
  sql-db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5432:5432
    # restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      - s3-bucket

  s3-bucket:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001' # This is used for webpage
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD} # pwd should be at least 8 char long
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

volumes:
  redis-stream:
    driver: local

  minio_data:
    driver: local

networks:
  minionetwork:
    driver: bridge
