services:
  butcher:
    build: .
    container_name: butcher
    environment:
      WORKING_DIR: WORKSPACE
      PORT: 3030
      DEBUG: NO
      S3_HOST: s3-bucket:9000
      S3_KEY: ${S3_KEY}
      S3_PWD: ${S3_PWD}
      S3_DEV_MODE: YES
      S3_BUCKET_NAME: video-files
      EMBED_QUEUE_URL: http://embeder:4040/API/add-to-queue
    command: ["gunicorn", "-w", "3", "'app:app'"]
    ports:
      - '3030:3030'
    networks:
      -  db_backend-net

networks:
  db_backend-net:
    external: true