version: '3.8'

services:
  embeder:
    build: .
    container_name: embeder
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PWD: ${POSTGRES_PASSWORD}
      DB_DATABASE_NAME: VIDEO_INFOMATION
      REDIS_SERVER_HOST: redis
      REDIS_SERVER_PORT: 6379
      REDIS_QUEUE_NAME: embed_tickets
      PORT: 4040
    ports:
      - '4040:4040'
    networks:
      -  db_backend-net

networks:
  db_backend-net:
    external: true

