services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    networks:
      -  db_backend-net

networks:
  db_backend-net:
    external: true
